### ISSUE TITLE
RuntimeError: stack expects a non-empty TensorList

### ISSUE THREAD

**Issue by shravankumar147** [DAVEISHAN/SPAct#4]
../datasets/vispr/train2017/2017_96697885.jpg has 4 channels
Traceback (most recent call last):
  File "train_ssl_minimax2.py", line 630, in <module>
    train_classifier(str(run_id), args.restart, None, args.kin_pretrained)
  File "train_ssl_minimax2.py", line 493, in train_classifier
    fa_model, fb_model, ft_model = train_epoch(run_id, epoch, train_dataloader_vispr, train_dataloader_ucf101, ft_model, fa_model, fb_model,  criterion_ft, criterion_fb, optimizer_fa, optimizer_fb, optimizer_ft, writer, use_cuda,learning_rate_fa, learning_rate_fb, learning_rate_ft)
  File "train_ssl_minimax2.py", line 57, in train_epoch
    for i, (data1, data2) in enumerate(zip(data_loader_vispr, dataloader_ucf101)):
  File "/opt/omniai/software/Miniconda/envs/face/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/opt/omniai/software/Miniconda/envs/face/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/opt/omniai/software/Miniconda/envs/face/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/opt/omniai/software/Miniconda/envs/face/lib/python3.6/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 4.
Original Traceback (most recent call last):
  File "/opt/omniai/software/Miniconda/envs/face/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/omniai/software/Miniconda/envs/face/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/opt/omniai/work/instance1/jupyter/github_contrib/data_anonimization/anonymization_training/dl_vispr_ssl.py", line 223, in collate_fn_train
    img1 = torch.stack(img1, dim=0)
RuntimeError: stack expects a non-empty TensorList

**Comment by shravankumar147** [comment]
This is due to failed image load, make sure to have img1 loaded.
